FROM centos:6

RUN yum install -y epel-release && yum clean all
RUN yum -y install nginx wget pcre-devel openssl-devel libxslt-devel gd-devel perl-ExtUtils-Embed GeoIP-devel google-perftools-devel && yum clean all
RUN yum -y groupinstall 'Development Tools' && yum clean all

WORKDIR /root

RUN NGINX_VERSION=`nginx -v 2>&1 | gawk 'match($0,/nginx version: nginx\/([0-9\.]+?)/,a) {print a[1]}'` && \
    echo $NGINX_VERSION && \
    wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz && \
    tar -xzvf nginx-$NGINX_VERSION.tar.gz && \
    mv /root/nginx-$NGINX_VERSION /root/nginx && \
    rm nginx-$NGINX_VERSION.tar.gz

WORKDIR /root/nginx

COPY compile.rh.sh /root/nginx/compile.sh
COPY nginx.conf /etc/nginx/nginx.conf

RUN chmod +x /root/nginx/compile.sh

CMD ["/root/nginx/compile.sh"]
