name: Release stable release

on:
    release:
        types: [released]

jobs:
    trigger-circleci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                distribution:
                    - buster
                    - bullseye
                    - bookworm
                    - focal
                    - jammy
                    - noble
                    - centos_7
                    - centos_8
        steps:
            -
                name: Set version
                env:
                    REF: ${{ github.ref }}
                run: VERSION=`sed -E 's/[^0-9]+?([0-9]+\.[0-9]+\.[0-9]+.+?)/\1/' <<< $REF` && echo "VERSION=$VERSION" >> $GITHUB_ENV

            -
                name: Set major version
                run: MAJOR_VERSION=`sed -E 's/[^0-9]+?([0-9]+)\.([0-9]+)\.([0-9]+).+?/\1/' <<< $VERSION` && echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

            -
                name: Trigger workflow
                env:
                    GH_TOKEN: ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}
                run: |
                    gh workflow run release.yml -R jolicode/redirection.io -f environment=production -f package=module-nginx -f channel=stable -f version=$VERSION -f version_directory=$MAJOR_VERSION -f build_iteration=1 -f module_image=${{ matrix.distribution }}
